### ISSUE TITLE
Dig into additional breaks behavior

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/regional_missense_constraint#216] opened 2022-07-28 16:01 UTC
Lily noticed that the multiple breaks results look strange for CHD8 (gene with only a single break) -- she ran an additional breaks search in each of the two subsections and found that there should have been a second break. I also ran a break manually and found a second break.

We need to investigate why this break wasn't found before and if there was an error. This is especially strange because Lily reran an addiitonal breaks search on KCNQ2 and found the same breakpoints as before

**Comment by lw453** [comment] 2022-07-28 19:51
To elaborate, CHD8 has only one identified breakpoint recorded in `multiple_breaks.ht`. 
<img width="937" alt="image" src="https://user-images.githubusercontent.com/30123882/181619671-ba3c6ebd-7717-42e0-9e9d-23c919e4ed09.png">
But there are multiple strange things about these results:

1. The value of `break_2_max_chisq` for CHD8 is 16.8, higher than the significance threshold of 9.2
<img width="250" alt="image" src="https://user-images.githubusercontent.com/30123882/181620155-a091f69f-4a0e-44b2-8e63-dc9e99b2c748.png">

2. Multiple rows have `break_2_chisq` values higher than this "max" value of 16.8.
<img width="939" alt="image" src="https://user-images.githubusercontent.com/30123882/181620268-e46bcad2-80c0-451b-9a7f-d047c275767f.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/30123882/181620376-bdac1ce7-814f-46a8-9fad-ba56cecd9bde.png">

3. Running a "second break" i.e. "additional break" search on CHD8 using the notebook at `gs://regional_missense_constraint/notebooks/rmc_investigation.ipynb` uncovers a breakpoint at 14:21896259 with a chi-square of 26.4. 
<img width="397" alt="image" src="https://user-images.githubusercontent.com/30123882/181620668-2fe0eeb5-646b-42af-b98e-87e85132a369.png">
I validated the break search method here with KCNQ2 (which has 2 breaks discovered by single and additional break search), to verify it is correct. KC also independently ran her own additional break search on CHD8 with the same result.
This result here was actually already recorded in `multiple_breaks.ht` i.e. the algorithm had discovered this breakpoint but did not identify it as such (this is the true max chi-square).
<img width="421" alt="image" src="https://user-images.githubusercontent.com/30123882/181621558-c6ef554a-3418-4047-bf8d-b495905e3b10.png">

4. This "missed" breakpoint at 14:21896259 also appears to be real, as it aligns with a breakpoint found in ExAC, bounds the locations of pathogenic ClinVar variants, and aligns with the beginning of a protein domain.
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/30123882/181624984-3927728d-7544-41f7-b9db-f80edc986c52.png">

**Comment by lw453** [comment] 2022-07-29 02:12
Zooming out to look across all 2955 transcripts in `multiple_breaks.ht` that underwent additional break search, up to 1495 transcripts have the same issue of having at least one row with `break_n_chisq` higher than `break_n_max_chisq`. Of these, up to 474 transcripts (including all of the 1495 where `n` is the 3rd or higher break) have `break_n_chisq` > 6.6. So we are potentially missing additional breakpoints in up to 474 transcripts (though this is only for additional breaks search so it would not affect produce new evidence of RMC in transcripts that do not already have a single break).
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/30123882/181666266-e45ef10e-41a4-4a98-b8d7-03fe753469c4.png">
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/30123882/181666357-9d9c8bf8-0f31-4e4b-8854-eadc7ddeabee.png">
I checked another of these transcripts, CHD2, where we are potentially missing a breakpoint. We are only calling one break, but there is a second locus with a value of 22.2 in `break_2_chisq` and only 2.72 in `break_2_max_chisq` that likely should be but is not called as a breakpoint. Again, it aligns with a breakpoint called in ExAC and bounds the locations of ClinVar P/LP variants — likely real.
<img width="985" alt="image" src="https://user-images.githubusercontent.com/30123882/181668112-436cbd49-4d22-4834-af5e-31159b94c75e.png">
<img width="785" alt="image" src="https://user-images.githubusercontent.com/30123882/181668187-f082e607-1fa0-473d-847f-add09a9b4747.png">

<img width="812" alt="image" src="https://user-images.githubusercontent.com/30123882/181668071-ec4e143e-8477-4321-b4e0-35d7a4cfb759.png">

**Comment by lw453** [comment] 2022-08-04 20:06
I am rerunning the additional breaks search so that we can dig into the intermediate results to identify the cause of this issue. Here are the details on that, for future reference:

Opened new branch `addtl_breaks_check`, code at https://github.com/broadinstitute/regional_missense_constraint/commit/edd750ae7472d77c495828182220313d2eb1a6b0

Start cluster:
```
hailctl dataproc start lw --master-machine-type n1-highmem-8 --worker-machine-type n1-highmem-8 --project broad-mpg-gnomad --num-workers 100 --pkgs="git+https://github.com/broadinstitute/gnomad_methods.git@main" --worker-boot-disk-size=200 --master-boot-disk-size=200  --max-idle=30m --labels=gnomad_release=gnomad_v2,rmc_step=investigate_additional_breaks --requester-pays-allow-all
```

Submit job:
```
hailctl dataproc submit lw pipeline/regional_constraint.py --search-for-additional-breaks --slack-channel "@Lily Wang" --chisq-threshold 6.6
```

**Comment by lw453** [comment] 2022-08-08 16:20
I did an initial run of additional break search for `break_num=2`, i.e. a search for the first additional break after a single break. Strangely, the issue seems to be resolved. Looking in `gs://regional_missense_constraint/temp/multiple_breaks.ht`:

CHD8 has the correct expected `max_chisq` value.
![image.png](https://images.zenhubusercontent.com/61e1a01361794dba718ab014/ab13ab36-05a8-4b9e-a8af-c168284b8e97)
![image.png](https://images.zenhubusercontent.com/61e1a01361794dba718ab014/b36af457-6f9a-4d57-bc4a-4f93e5ad44e5)

And no more transcripts have a locus with `chisq > max_chisq` (1333 before).
![image.png](https://images.zenhubusercontent.com/61e1a01361794dba718ab014/5406ef55-4938-441c-aaf8-af8626b5cb35)

**Comment by lw453** [comment] 2022-08-08 19:19
Based on this run, there are actually 496 transcripts with additional breaks.
![image.png](https://images.zenhubusercontent.com/61e1a01361794dba718ab014/c3461947-239c-44bc-a7b7-c07b56254bc7)

Our freeze identifies 153 transcripts with additional breaks — this increases our yield by more than three-fold.

**Comment by lw453** [comment] 2022-08-08 20:46
More issues we found, in additional breaks logic:

1. Section annotation in `finalize_multiple_breaks` may not be handled correctly in cases where multiple additional breaks are found in a transcript in one loop iteration (i.e. multiple loci in a transcript have `True` in the same index of `break_list`).
a. This was fixed in the cleanup PR that was closed without review.
2. Splitting transcripts into sections in `process_additional_breaks` prior to break search, for all iterations of additional break search after `break_num=2`.
![image.png](https://images.zenhubusercontent.com/61e1a01361794dba718ab014/8e2a691b-c954-4c5e-ac8a-1308da79608c)
![image.png](https://images.zenhubusercontent.com/61e1a01361794dba718ab014/5ebec1de-1a03-4a5f-aeda-b2798b4abb4d)
a. The transcript will always be split into two sections to search — before and after the breakpoint identified in the previous additional break search iteration.
3. Splitting transcripts into sections in `process_additional_breaks` prior to break search, in cases where multiple additional breaks are found in a transcript in one loop iteration.
a. In these cases,`break_ht` in the above screenshot will have multiple rows for a transcript but is keyed by transcript so the join will have unintended behavior.

Given our intention to pivot to a generalized, recursive workflow that ties the single/additional break and simultaneous break search paths together, we are going to move directly to implementing the new workflow (in a way that resolves any of the above issues as applicable) rather than just fixing additional break search.

**Closed by lw453** 2022-08-08 20:46 UTC
Labels: unplanned
